### ISSUE TITLE
Ban randomly when time expires

### ISSUE THREAD

**Issue by cesaroeduardo** [bepizu/pokemonunite-draft-simulation-website#1]
**Describe the bug**
Notado que quando o tempo estoura o simulador bane aleatoriamente um pokémon.

**To Reproduce**
1. Dar start
2. Esperar os 20s para o ban

**Expected behavior**
A ação esperada seria não banir nada.

**Comment by userBarbosa** [comment]
@cesaroeduardo, no game o ban também é randômico, tanto caso não escolha como caso a quantidade de votos seja a mesma pra diferentes pokemons.
Da uma olhada nesse exemplo:
https://youtu.be/cAmrNYn-Mt0

**Comment by cesaroeduardo** [comment]
Checado aqui, realmente é randomico, erro meu, isso que dá não jogar competitivo e achar que é igual ao lol. Fechando aqui.
