### ISSUE TITLE
Start clicking in pokémon bugs top bar

### ISSUE THREAD

**Issue by cesaroeduardo** [bepizu/pokemonunite-draft-simulation-website#2]
**Describe the bug**
É possível começar os picks sem dar start, o que faz a top bar não iniciar os contadores.

**To Reproduce**
1. Não clicar em start
2. Clicar em um pokémon

**Expected behavior**
O esperado é dar inicio ao contador, ou não permitir o clique inicial nos pokémons.

**Comment by userBarbosa** [comment]
@cesaroeduardo na verdade o comportamento esperado é existir a possibilidade de fazer os picks sem iniciar o contador, dessa forma não há a pressão e o usuário pode usufruir de informações como stats dos pokemons e etc.

**Comment by cesaroeduardo** [comment]
Faz sentido, vou adicionar na minha fila aqui de interface uma forma de apresentar pro usuário essa possibilidade, após, adiciono como enhancement aqui. Valeu @userBarbosa.
